project: "FrozenLake"
name: "Qwen3-1.7B-agent"
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: multi_step_grpo
  repeat_times: 8
  kl_loss_fn: "low_var_kl"
  optimizer:
    lr: 1e-6
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen3-1.7B}
  max_response_tokens: 1024
  max_model_len: 25600
  temperature: 0.7
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 32
  train_batch_size: 2048
  explorer_input:
    taskset:
      name: frozenlake
      storage_type: file
      path: ${oc.env:TRINITY_TASKSET_PATH}
      split: train
      workflow_args:
        env_max_steps: 8
        agent_max_steps: 10
        is_slippery: false
    eval_tasksets:
      - name: frozenlake
        storage_type: file
        path: ${oc.env:TRINITY_TASKSET_PATH}
        split: test
        workflow_args:
          env_max_steps: 8
          agent_max_steps: 10
          is_slippery: false
        repeat_times: 4
        rollout_args:
          temperature: 0.1
    default_workflow_type: 'examples.agentscope_frozenlake.workflow.FrozenLakeWorkflow'
explorer:
  eval_on_startup: true
  eval_interval: 20
  runner_per_model: 8
  rollout_model:
    engine_num: 6
    tensor_parallel_size: 1
    enable_chunked_prefill: true
    enforce_eager: false
    enable_openai_api: true
    enable_history: true
    enable_auto_tool_choice: true
    tool_call_parser: hermes
    reasoning_parser: deepseek_r1
    enable_thinking: true
    dtype: bfloat16
    seed: 42
    gpu_memory_utilization: 0.85
trainer:
  save_interval: 100
  use_dynamic_bsz: true
  grad_clip: 1.0
  ulysses_sequence_parallel_size: 2

synchronizer:
  sync_method: nccl
  sync_style: dynamic_by_explorer
  sync_interval: 1
  sync_timeout: 1200
