name: unittest

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  unittest:
    # only run on pull request
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/run-unittest') && github.event.comment.author_association == 'COLLABORATOR' }}
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        path: trinity-${{ github.run_id }}

    - name: Setup docker compose
      working-directory: trinity-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose up -d
        sleep 5s

    - name: Check ray status
      working-directory: trinity-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec trinity-node-1 ray status
        docker compose exec trinity-node-2 ray status

    - name: Run unittest
      working-directory: trinity-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec trinity-node-1 pytest tests --ignore=tests/data --ctrf report.json
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: trinity-${{ github.run_id }}/report.json

    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: trinity-${{ github.run_id }}/report.json
        pull-request-report: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()
# TODO: run data tests after the dependency conflict is resolved
